[package]
name = "vppmake"
version = "0.1.0"
edition = "2024"


[dependencies]
ahash = { version = "0.8.12", features = ["serde"] }
anyhow = "1.0.101"
indexmap = { version = "2.13.0", features = ["serde"] }
kstring = { version = "2.0.2", features = ["arc", "serde"] }
reqwest = "0.13.1"
rustemon = "4.4.0"
scraper = "0.25.0"
serde = { version = "1.0.228", features = ["derive", "rc"] }
smallvec = "1.15.1"
tokio = { version = "1.49.0", features = ["full"] }
toml = "0.9.11"
toml_edit = "0.24.0"
